In [1]:
import sys
import pandas as pd
import requests

print(sys.executable)
print(sys.version)

d:\PersonalProjects\England_convocatory_comparison_WC2026\.venv\Scripts\python.exe
3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]

In [2]:
import os

print(os.getcwd())

d:\PersonalProjects\England_convocatory_comparison_WC2026\notebooks

In [3]:
# Loading CSV
df = pd.read_csv("../data/raw/csv/standard_stats_top5_leagues.csv", header=1)
df.info() # All strings

<class 'pandas.DataFrame'>
RangeIndex: 2952 entries, 0 to 2951
Data columns (total 26 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rk
▲     2952 non-null   str
 1   Player   2952 non-null   str
 2   Nation   2949 non-null   str
 3   Pos      2952 non-null   str
 4   Squad    2952 non-null   str
 5   Comp     2952 non-null   str
 6   Age      2950 non-null   str
 7   Born     2950 non-null   str
 8   MP       2952 non-null   str
 9   Starts   2952 non-null   str
 10  Min      2952 non-null   str
 11  90s      2952 non-null   str
 12  Gls      2952 non-null   str
 13  Ast      2952 non-null   str
 14  G+A      2952 non-null   str
 15  G-PK     2952 non-null   str
 16  PK       2952 non-null   str
 17  PKatt    2952 non-null   str
 18  CrdY     2952 non-null   str
 19  CrdR     2952 non-null   str
 20  Gls.1    2952 non-null   str
 21  Ast.1    2952 non-null   str
 22  G+A.1    2952 non-null   str
 23  G-PK.1   2952 non-null   str
 24  G+A-PK   2952 non-null   str
 25  Matches  2952 non-null   str
dtypes: str(26)
memory usage: 599.8 KB

In [4]:
# Fixing the Minutes column, comas 
df["Min"] = pd.to_numeric(
    df["Min"].str.replace(",", "", regex=False),
    errors="coerce"
)

In [5]:
# Checking type "Min"
df["Min"].dtype

df.info() # All strings, except for the Minutes column

<class 'pandas.DataFrame'>
RangeIndex: 2952 entries, 0 to 2951
Data columns (total 26 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rk
▲     2952 non-null   str
 1   Player   2952 non-null   str
 2   Nation   2949 non-null   str
 3   Pos      2952 non-null   str
 4   Squad    2952 non-null   str
 5   Comp     2952 non-null   str
 6   Age      2950 non-null   str
 7   Born     2950 non-null   str
 8   MP       2952 non-null   str
 9   Starts   2952 non-null   str
 10  Min      2839 non-null   float64
 11  90s      2952 non-null   str
 12  Gls      2952 non-null   str
 13  Ast      2952 non-null   str
 14  G+A      2952 non-null   str
 15  G-PK     2952 non-null   str
 16  PK       2952 non-null   str
 17  PKatt    2952 non-null   str
 18  CrdY     2952 non-null   str
 19  CrdR     2952 non-null   str
 20  Gls.1    2952 non-null   str
 21  Ast.1    2952 non-null   str
 22  G+A.1    2952 non-null   str
 23  G-PK.1   2952 non-null   str
 24  G+A-PK   2952 non-null   str
 25  Matches  2952 non-null   str
dtypes: float64(1), str(25)
memory usage: 599.8 KB

In [6]:
# df with english fotballers only, and copy to avoid SettingWithCopyWarning
eng = df[df["Nation"].str.contains("ENG", na=False)].copy()
# Checking type
print(eng["Min"].dtype)

float64

In [7]:
# values Minutes
eng["Min"].sample(20)

2465    1001.0
2787     617.0
2338     876.0
1219    1487.0
1712    1168.0
268     1786.0
714      688.0
1580      37.0
1139    3330.0
1165    1741.0
1912     561.0
1492     407.0
1452    1764.0
1110    2181.0
1010     888.0
2238       4.0
2278       1.0
2419    1823.0
2        164.0
2763    1251.0
Name: Min, dtype: float64

In [8]:
eng.info() # All strings, except Minutes

<class 'pandas.DataFrame'>
Index: 199 entries, 1 to 2787
Data columns (total 26 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rk
▲     199 non-null    str
 1   Player   199 non-null    str
 2   Nation   199 non-null    str
 3   Pos      199 non-null    str
 4   Squad    199 non-null    str
 5   Comp     199 non-null    str
 6   Age      199 non-null    str
 7   Born     199 non-null    str
 8   MP       199 non-null    str
 9   Starts   199 non-null    str
 10  Min      199 non-null    float64
 11  90s      199 non-null    str
 12  Gls      199 non-null    str
 13  Ast      199 non-null    str
 14  G+A      199 non-null    str
 15  G-PK     199 non-null    str
 16  PK       199 non-null    str
 17  PKatt    199 non-null    str
 18  CrdY     199 non-null    str
 19  CrdR     199 non-null    str
 20  Gls.1    199 non-null    str
 21  Ast.1    199 non-null    str
 22  G+A.1    199 non-null    str
 23  G-PK.1   199 non-null    str
 24  G+A-PK   199 non-null    str
 25  Matches  199 non-null    str
dtypes: float64(1), str(25)
memory usage: 42.0 KB

In [9]:
# Only english players with +800 minutes played
eng_800 = eng[eng["Min"] >= 800]
print(f"Number of English players: {len(eng)}")
print(f"Number of English players with more than 800 minutes played: {len(eng_800)}")

Number of English players: 199
Number of English players with more than 800 minutes played: 108

In [10]:
# Saving English players with more than 800 minutes played in a CSV
eng_800.to_csv("../data/processed/eng_players_800min.csv", index=False)

In [11]:
# Checking name positions by player
eng_800["Pos"].value_counts()

Pos
MF       37
DF       25
DF,MF    11
FW        9
MF,DF     8
FW,MF     7
MF,FW     6
GK        5
Name: count, dtype: int64

In [12]:
# Identify every row per player, checking for merge in a few steps
eng_800[
    ["Player", "Squad", "Comp"]
].duplicated().sum()

np.int64(0)

In [13]:
# We get shooting stats too, load csv
shooting = pd.read_csv(
    "../data/raw/csv/shooting_stats.csv",
    header=1
)

print(shooting.shape)

shooting.head()

(2952, 20)

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,24,2000,27.2,4,47,17,36.2,1.73,0.62,0.09,0.24,0,0,Matches
1,2,Jerome Abbey,eng ENG,MF,Wolves,eng Premier League,15,2009,0.2,0,0,0,NaN,0.00,0.00,NaN,NaN,0,0,Matches
2,3,Zach Abbott,eng ENG,DF,Nottingham,eng Premier League,19,2006,1.8,0,0,0,NaN,0.00,0.00,NaN,NaN,0,0,Matches
3,4,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,19,2006,7.6,2,17,4,23.5,2.25,0.53,0.12,0.50,0,0,Matches
4,5,Himad Abdelli,dz ALG,MF,Marseille,fr Ligue 1,25,1999,1.5,0,4,1,25.0,2.61,0.65,0.00,0.00,0,0,Matches

In [14]:
# Checking possible duplicates
print(shooting.shape)

shooting[
    ["Player", "Squad", "Comp"]
].duplicated().sum()

(2952, 20)

np.int64(112)

In [15]:
# Checking specific duplicates
dupes = shooting[
    shooting.duplicated(
        subset=["Player", "Squad", "Comp"],
        keep=False
    )
]

dupes.sort_values(
    ["Player", "Squad", "Comp"]
).head(30)

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
25,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
51,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
77,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
103,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
129,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
155,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
181,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
207,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
233,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
259,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
285,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
311,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
337,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
363,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
389,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
415,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
441,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
467,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
493,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
519,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
545,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
571,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
597,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
623,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
649,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
675,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
701,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
727,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
753,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
779,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches

In [16]:
# How many players duplicates are
shooting["Player"].value_counts().head(20)

Player
Player                113
Nicolás González        3
Himad Abdelli           2
Simon Adingra           2
Nayef Aguerd            2
Ilias Akhomach          2
Alfon                   2
Aaron Anselmino         2
Leon Bailey             2
Darryl Bakola           2
Dilane Bakwa            2
Tommaso Baldanzi        2
Sheraldo Becker         2
Jeanuël Belocian        2
Fran Beltrán            2
Eliesse Ben Seghir      2
Oscar Bobb              2
Jeremie Boga            2
Badredine Bouanani      2
Marco Brescianini       2
Name: count, dtype: int64

In [17]:
# "Player" duplicates
shooting[
    shooting["Player"] == "Player"
]

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
25,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
51,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
77,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
103,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
129,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2833,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
2859,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
2885,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
2911,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
2937,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches

In [ ]:
# Copy without Player duplicates
shooting = shooting[
    shooting["Player"] != "Player"
].copy()

In [ ]:
# Checking shape
shooting.shape

(2839, 20)

In [ ]:
# Checking again duplicates
shooting[
    ["Player", "Squad", "Comp"]
].duplicated().sum()

np.int64(0)

In [ ]:
# Seems well
shooting.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,24,2000,27.2,4,47,17,36.2,1.73,0.62,0.09,0.24,0,0,Matches
1,2,Jerome Abbey,eng ENG,MF,Wolves,eng Premier League,15,2009,0.2,0,0,0,NaN,0.00,0.00,NaN,NaN,0,0,Matches
2,3,Zach Abbott,eng ENG,DF,Nottingham,eng Premier League,19,2006,1.8,0,0,0,NaN,0.00,0.00,NaN,NaN,0,0,Matches
3,4,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,19,2006,7.6,2,17,4,23.5,2.25,0.53,0.12,0.50,0,0,Matches
4,5,Himad Abdelli,dz ALG,MF,Marseille,fr Ligue 1,25,1999,1.5,0,4,1,25.0,2.61,0.65,0.00,0.00,0,0,Matches

In [23]:
# Function to clean every dataframe from FBRef
def load_fbref_table(path: str) -> pd.DataFrame:
    """
    Load and clean a FBref table exported as CSV.

    FBref repeats table headers every 25 rows when exporting
    large tables. This function removes those duplicated
    header rows and returns a clean DataFrame.

    Args:
        path (str): Path to the FBref CSV file.

    Returns:
        pd.DataFrame: Cleaned FBref table.
    """
    df = pd.read_csv(path, header=1)

    return (
        df[df["Player"] != "Player"]
        .copy()
        .reset_index(drop=True)
    )